<div class="col-sm-12 col-md-9 col-lg-9 col-xl-10">
	<div class="panel">
		<h4><img class="glyph-icon-24" src="<?= SVG_PATH?>si-glyph-trash.svg"> {wastebin}</h4>
	</div>
	<table class="table table-hover table-striped">
		<thead>
			<tr>
				<th>#</th>
				<th>{date}</th>
				<th>{title}</th>
				<th>{content}</th>
				<th>{actions}</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($itemList as $item ): ?>
            <tr>
                <td></td>
                <td><?= strftime('%d.%m.%Y', $item['datetime']); ?></td>
                <td><?= $item['title']; ?></td>
                <td><?= $item['content_type']; ?></td>
                <td>
                	<a href="#">
    	           		<img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-delete.svg" title="{delete}">
                   	</a>
                </td>
            </tr>
        <?php endforeach; ?>
		</tbody>
	</table>
<!-- 
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<a href="##placeholder-uri##" class="btn btn-primary" role="button">##placeholder-button##</a>
	</div>
</div>
-->
</div>