<div class="row">
   	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="alert alert-light" role="alert">
  			<h4>Es wurden noch keine Seiten erstellt!</h4>
  			<hr>
  			<p>Hier können sie neue Seiten einfach verfassen und ausgeben.</p>
  			<p>Diese werden anschließend der öffentlichkeit präsentiert. Wollen sie den angefangenen
  			Artikel noch nicht publizieren, stellen sie den Artikel einfach auf unsichtbar.</p>
		</div>
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    		<a href="/../page/new" class="btn btn-primary" role="button">{create_page}</a>
		</div>
   	</div>
</div>