CREATE DATABASE heinercms;

USE heinercms;

CREATE TABLE articles (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(64) NOT NULL DEFAULT '',
  content LONGTEXT NOT NULL,
  datetime DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  nextPageId INT NOT NULL DEFAULT '-1',
  visible TINYINT(4) NOT NULL DEFAULT '0'
);

CREATE TABLE downloads (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(64) NOT NULL DEFAULT '',
  comment TEXT NOT NULL,
  path VARCHAR(128) NOT NULL DEFAULT '',
  filename VARCHAR(64) NOT NULL DEFAULT '',
  datetime DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  visible TINYINT(4) NOT NULL DEFAULT '0'
);

CREATE TABLE links (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(64) NOT NULL DEFAULT '',
  uri VARCHAR(255) NOT NULL DEFAULT 'http://',
  comment TEXT NOT NULL,
  visible TINYINT(4) NOT NULL DEFAULT '0'
);

CREATE TABLE news (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(64) NOT NULL DEFAULT '',
  message TEXT NOT NULL,
  datetime DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  visible TINYINT(4) NOT NULL DEFAULT '0'
);

CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL DEFAULT '',
  password VARCHAR(255) NOT NULL DEFAULT '',
  email VARCHAR(255) NOT NULL DEFAULT '',
  active ENUM('true','false') NOT NULL DEFAULT 'false',
  UNIQUE KEY username (username),
  UNIQUE KEY email (email)
);
