<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="<?= BASE_URL; ?>admin/index">heinerCMS - {administration}</a>
    <ul class="nav justify-content-end">
        <li class="nav-item">
        	<a class="nav nav-link dark" href="<?= BASE_URL; ?>user/logout">{sign_out}</a>
        </li>
    </ul>
</nav>
<div class="navigation">
<div class="navi" style="width:20em;">
    <!-- Dashboard -->
	<div class="list-group spacing">
        <a href="<?= BASE_URL; ?>admin/index" class="list-group-item list-group-item-action active">
            <img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-dashboard.svg"> {dashboard}
        </a>
	</div>

    <!-- Content -->
    <div class="list-group spacing">
        <span class="list-group-item active">
            {content}
        </span>
            <a href="<?= BASE_URL; ?>article/index" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-pen.svg"> {article}
                <span class="badge badge-light"></span>
            </a>
            <a href="<?= BASE_URL; ?>download/index" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-file-download.svg"> {downloads}
                <span class="badge badge-light"></span>
            </a>
            <a href="<?= BASE_URL; ?>link/index" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-global.svg"> {links}
                <span class="badge badge-light"></span>
            </a>
            <a href="<?= BASE_URL; ?>page/index" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-document.svg"> {pages}
                <span class="badge badge-light"></span>
            </a>
            <a href="<?= BASE_URL; ?>wastebin/index" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-trash.svg"> {wastebin}
                <span class="badge badge-light"></span>
            </a>
    </div>

    <!-- Communication -->
    <!-- <div class="list-group spacing">
        <span class="list-group-item active">
            <span class="glyphicon glyphicon-book" aria-hidden="true"></span> Kommunikation
        </span>
            <a href="index.php?uri=communication" class="list-group-item list-group-item-action">
                Kontakt anfragen
                <span class="badge badge-light">0##placeholder-inqiery##</span>
            </a>
    </div> -->

    <!-- Settings -->
    <div class="list-group spacing">
        <span class="list-group-item active">
            {settings}
        </span>
            <a href="<?= BASE_URL; ?>admin/settings" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-gear.svg"> {general}
            </a>
            <a href="<?= BASE_URL; ?>admin/mainpage" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-home-page.svg"> {mainpage}
            </a>
            <a href="<?= BASE_URL; ?>article/settings" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-pen.svg"> {article}
            </a>
            <a href="<?= BASE_URL; ?>download/settings" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-file-download.svg"> {downloads}
            </a>
            <a href="<?= BASE_URL; ?>link/settings" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-global.svg"> {links}
            </a>

            <a href="<?= BASE_URL; ?>user/index" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-person-people.svg"> {user}
            </a>
    </div>
</div>
</div>
