		</div>
	</div>
</div>
		<footer>
			<div class="footer-text">
				<p>&copy; 2017 - 2019 Heinrich-Schiller.de</p>
				<p><i>powered by heinerCMS</i></p>
			</div>
		</footer>
		<!-- TinyMCE-Editor -->
		<script src="/vendor/tinymce/tinymce/tinymce.min.js"></script>
  		<script>tinymce.init({ selector:'textarea#text'});</script>

  		<script src="/public/assets/js/main.js"></script>
    </body>
</html>
