<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="<?= BASE_URL; ?>public/index">Heinrich-Schiller.de</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
		<div class="navbar-nav">
			<a class="nav-item nav-link" href="<?= BASE_URL; ?>wordpress" target="_blank" rel="noopener">{blog}</a>
			<?php if($entry[1] ==! 0): ?>
				<a class="nav-item nav-link" href="<?= BASE_URL; ?>public/downloads">{downloads}</a>
			<?php endif; ?>

			<?php if($entry[2] ==! 0): ?>
				<a class="nav-item nav-link" href="<?= BASE_URL; ?>public/links">{links}</a>
			<?php endif; ?>

			<?php if($entry[3] ==! 0): ?>
				<a class="nav-item nav-link" href="<?= BASE_URL; ?>public/page">{page}</a>
			<?php endif; ?>

			<?php if($entry[0] ==! 0): ?>
				<a class="nav-item nav-link" href="<?= BASE_URL; ?>public/articles">{article}</a>
			<?php endif; ?>
			<!-- <a class="nav-item nav-link" href="/../public/pages">{pages}</a> -->
			<a class="nav-item nav-link" href="<?= BASE_URL; ?>user/login">{sign_in}</a>
		</div>
	</div>
</nav>
