<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="/../public/index">Heinrich-Schiller.de</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
		<div class="navbar-nav">
			<a class="nav-item nav-link" href="#">{blog}</a>
			<a class="nav-item nav-link" href="/../public/downloads">{downloads}</a>
			<a class="nav-item nav-link" href="/../public/links">{links}</a>
			<a class="nav-item nav-link" href="/../public/articles">{article}</a>
			<!-- <a class="nav-item nav-link" href="/../public/pages">{pages}</a> -->
			<a class="nav-item nav-link" href="/../user/login">{sign_in}</a>
		</div>
	</div>
</nav>
