<div class="col-sm-12 col-md-3 col-lg-2 col-xl-9">
   		<div class="panel">
   			<h4><img class="glyph-icon-24" src="<?= SVG_PATH; ?>si-glyph-pen.svg"> {pages}</h4>
   		</div>

        <?php if(count($pages) > 0): ?>

        <table class="table table-hover table-striped">
        	<thead>
        		<tr>
        			<th>#</th>
        			<th>{date}</th>
        			<th>{title}</th>
        			<th>{visible}?</th>
        			<th>{actions}</th>
        		</tr>
        	</thead>
        	<tbody>
        		<?php foreach($pages as $page): ?>
        		<tr class="clickable-row" data-href="<?= BASE_URL; ?>page/edit/id/<?= $page['id']; ?>">
                    <td></td>
                    <td><?= strftime('%d.%m.%Y', $page['datetime']); ?></td>
                    <td><?= $page['title']; ?></td>
                    <td><?= ($page['visibility'] === 'true') ? '{yes}' : '{no}'; ?></td>
            		<td>
            			<a href="#">
                            <img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-document-copy.svg" title="{copy}">
                        </a> &middot;
                    	<a href="<?= BASE_URL; ?>page/del/id/<?= $page['id']; ?>">
                            <img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-delete.svg" title="{delete}">
                        </a>
                    </td>
                </tr>
                <?php endforeach; ?>
        	</tbody>
        </table>
    	<div >
    		<a href="/../page/new" class="btn btn-primary" role="button">{create_page}</a>
    	</div>

        <?php else: ?>

        <div class="row">
           	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        		<div class="alert alert-light" role="alert">
          			<h4>Es wurden noch keine Seiten erstellt!</h4>
          			<hr>
          			<p>Hier können sie neue Seiten einfach verfassen und ausgeben.</p>
        		</div>
        		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            		<a href="<?= BASE_URL; ?>page/new" class="btn btn-primary" role="button">{create_page}</a>
        		</div>
           	</div>
        </div>

        <?php endif; ?>
</div>
