<div class="container-fluid">
    <div class="jumbotron">
    	<div class="container">
    		<h1 class="display-4">{article}</h1>
    		<p class="lead"><?= $settings['tagline']; ?></p>
    	</div>
    </div>
    <div class="container">
    	<?= $settings['text']; ?>
    </div>
    <div class="container">
    <?php foreach ($articles as $article): ?>
    	<div class="row">
        	<div class="col-md-12">
        		<ul class="list-group">
                	<li class="list-group-item public"><?= $article['title']; ?>
                		<span class="article-datetime"><?= strftime('%d.%m.%Y', $article['datetime']); ?></span>
                	</li>
                	<li class="list-group-item"><?= $article['text']; ?> ...</li>
                	<li class="list-group-item"><a href="/../public/article/id/<?php echo $article['id']; ?>">weiterlesen</a></li>
        		</ul>
        	</div>
        </div>
        <br>
    <?php endforeach; ?>
    </div>
</div>
