<div class="container-fluid">
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-4">{downloads}</h1>
            <p class="lead"><?= $settings['tagline']; ?></p>
        </div>
    </div>
    <div class="container">
    	<?= (!empty($settings['text'])) ? $settings['text'] : ''; ?>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            <?php foreach($downloads as $download): ?>
                <ul class="list-group">
                	<li class="list-group-item public"><?= $download['title']?>
                		<span class="article-datetime"><?= strftime('%d.%m.%Y',$download['datetime']); ?></span>
                	</li>
                	<li class="list-group-item"><?=$download['text']?>
                	<li class="list-group-item"><a href="#">{download}</a></li>
                </ul>
                <br>
            <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>


