<div class="container-fluid">
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-4">{links}</h1>
            <p class="lead"><?= $settings['tagline']; ?></p>
        </div>
    </div>
    <div class="container">
        <?= (!empty($settings['text'])) ? $settings['text'] : ''; ?>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
            <?php foreach($links as $link): ?>
                <ul class="list-group">
                    <li class="list-group-item public">
                        <a href="<?= $link['uri']; ?>" target="blank"><?= $link['title']; ?> - <?= $link['tagline']; ?></a>
                    </li>
                    <li class="list-group-item"><?= $link['text']; ?></li>
                </ul>
                <br>
            <?php endforeach; ?>
    	    </div>
        </div>
    </div>
</div>
