<div class="jumbotron">
	<div class="container">
		<h1 class="display-4"><?= $settings['title']; ?></h1>
		<p class="lead"><?= $settings['tagline']; ?></p>
	</div>
</div>
<div class="container">
	<!-- Article -->
	<div class="content">
		<div class="row">

            <?php if(count($article) > 0): ?>

    		<article class="col-md-8">
            	<div class="article-title">
            		<strong>{current_article} - {author}</strong>&nbsp;<?= $article['author']; ?>
                    <span class="article-datetime">
                        <strong><?= strftime('%d.%m.%Y', $article['datetime']); ?></strong>
                    </span>
            	</div>
            	<h2>
                    <a class="content-header" href="<?= BASE_URL; ?>public/article/id/<?= $article['id']; ?>">
						<?= $article['title']; ?>
					</a>
                </h2>
            	<div>
            		<?= $article['text']; ?>
					<?php if($article['charCount'] > 2000): ?>
					...
					<div>
	            	<a class="readmore" href="<?= BASE_URL; ?>public/article/id/<?= $article['id']; ?>">{readmore}</a>
					</div>
					<?php endif; ?>
            	</div>
            </article>

            <?php else: ?>

            <div class="row">
               	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            		<div class="alert alert-light" role="alert">
              			<h3>Es wurden noch keine Artikel erstellt!</h3>
            		</div>
               	</div>
            </div>

            <?php endif; ?>

			<aside class="col-md-4">
				<div class="alert alert-success">
					<h4 class="alert-heading"><?= $info['title']; ?></h4>
					<?= $info['text']; ?>
				</div>
			</aside>
		</div>
	</div>
</div>
