<div class="row navi">
        		<div class="col-xl-3 col-lg-3 col-xs-12">
        			<!-- Dashboard -->
<div class="list-group spacing">
        <a href="/../admin/index" class="list-group-item list-group-item-action active">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-dashboard.svg"> Dashboard
        </a>
</div>

<!-- Content -->
<div class="list-group spacing">
    <span class="list-group-item active">
        Inhalt
    </span>
        <a href="index.php?uri=articles" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-pen.svg"> Artikel
            <span class="badge badge-light">3</span>
        </a>
        <a href="index.php?uri=downloads" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-file-download.svg"> Downloads
            <span class="badge badge-light">0</span>
        </a>
        <a href="index.php?uri=links" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-global.svg"> Links
            <span class="badge badge-light">0</span>
        </a>
        <a href="index.php?uri=pages" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-document.svg"> Seiten
            <span class="badge badge-light">0</span>
        </a>
        <a href="index.php?uri=trash" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-trash.svg"> Mülleimer
            <span class="badge badge-light">0</span>
        </a>
</div>

<!-- Communication -->
<div class="list-group spacing">
    <span class="list-group-item active">
        <span class="glyphicon glyphicon-book" aria-hidden="true"></span> Kommunikation
    </span>
        <a href="index.php?uri=communication" class="list-group-item list-group-item-action">
            Kontakt anfragen
            <span class="badge badge-light">0<!-- ##placeholder-inqiery##  --></span>
        </a>
</div>

<!-- Settings -->
<div class="list-group spacing">
    <span class="list-group-item active">
        Einstellungen
    </span>
        <a href="/../admin/settings" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-gear.svg"> Allgemein
        </a>
        <a href="index.php?uri=mainpage" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-home-page.svg"> Hauptseite
        </a>
        <a href="index.php?uri=articlessettings" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-pen.svg"> Artikel
        </a>
        <a href="index.php?uri=downloadssettings" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-file-download.svg"> Downloads
        </a>
        <a href="index.php?uri=linksettings" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-global.svg"> Links
        </a>
        
        <a href="index.php?uri=user" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-person-people.svg"> Benutzer
        </a>
</div>