<div class="col-sm-12 col-md-9 col-lg-9 col-xl-10">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-9">
            <div class="panel">
                <h4><img class="glyph-icon-24" src="<?= SVG_PATH; ?>si-glyph-file-download.svg"> {downloads}</h4>
            </div>

            <?php if(isset($download['id'])): ?>
            <form action="<?= BASE_URL;?>download/update" method="post">
            <?php else: ?>
            <form action="<?= BASE_URL;?>download/add" method="post">
            <?php endif; ?>

            	<div class="row">
            		<div class="col-2 col-sm-3 col-md-3 col-lg-3 col-xl-9">
            			<div class="form-group">
            				<label for="ident">#&nbsp;</label><span></span>
            				<input type="hidden" name="id" value="<?= isset($download['id']) ? $download['id'] : '{new}'; ?>">
            			</div>
            		</div>
            		<div class="col-10 col-sm-9 col-md-9 col-lg-9 col-xl-3">
            			<div class="form-group">
            				<p class="text-right">{date}: <?= isset($download['datetime']) ? strftime('%d.%m.%Y', $download['datetime']) : currentDatetime(); ?></p>
            			</div>
            		</div>
            	</div>
                <div class="form-group">
                    <label for="title">{title}:</label>
                    <input type="text" name="title" value="<?= isset($download['title']) ? $download['title'] : ''; ?>" class="form-control" id="title" required>
                </div>
                <div class="form-group">
                    <label for="path">{path}:</label>
                    <input type="text" name="path" value="<?= isset($download['path']) ? $download['path'] : ''; ?>" class="form-control" id="path" required>
                </div>
                <div class="form-group">
                    <label for="filename">{filename}:</label>
                    <input type="text" name="filename" value="<?= isset($download['filename']) ? $download['filename'] : ''; ?>" class="form-control" id="filename" required>
                </div>
                <div class="form-group">
                    <label for="comment">{text}:</label>
                    <textarea name="text" id="texteditor">
                        <?= isset($download['text']) ? $download['text'] : ''; ?>
                    </textarea>
                </div>
                </div>

                <!-- Options -->
                <div class="col-sm-12 col-md-12 col-lg-12 col-xl-3">
                    <div class="list-group spacing">
                        {options}
                	</div>
                    <span>{visible}?</span>
                    <div class="custom-control custom-radio custom-control-inline">
                        <input type="radio" id="customRadioInline1" name="visible" value="true" class="custom-control-input" <?= (isset($download['visibility']) && $download['visibility'] === 'true') ? 'checked' : ''; ?>>
                        <label class="custom-control-label" for="customRadioInline1">{yes}</label>
                    </div>
                    <div class="custom-control custom-radio custom-control-inline">
                        <input type="radio" id="customRadioInline2" name="visible" value="false" class="custom-control-input"  <?= (isset($download['visibility']) && $download['visibility'] === 'false' || !isset($download)) ? 'checked' : ''; ?>>
                        <label class="custom-control-label" for="customRadioInline2">{no}</label>
                    </div>
                </div>
                <!-- End options -->

                <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">{save}</button>
                        <span></span>
                        <button type="reset" class="btn btn-danger">{reset}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
