<div class="col-sm-12 col-md-9 col-lg-9 col-xl-10">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
        	<div class="panel">
        		<h4><img class="glyph-icon-24" src="<?= SVG_PATH; ?>si-glyph-dashboard.svg"> {dashboard}</h4>
        	</div>
			<div class="row">
				<div class="col-md-6">
					<div class="alert alert-light">
						<h4 class="alert-heading">{article}</h4>
						...
					</div>
				</div>
				<div class="col-md-6">
					<div class="alert alert-light">
						<h4 class="alert-heading">{downloads}</h4>
						...
					</div>
				</div>
				<div class="col-md-6">
					<div class="alert alert-light">
						<h4 class="alert-heading">{links}</h4>
						...
					</div>
				</div>
				<div class="col-md-6">
					<div class="alert alert-light">
						<h4 class="alert-heading">{pages}</h4>
						...
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
