<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="#">##placeholder-title## - {administration}</a>
    <ul class="nav justify-content-end">
        <li class="nav-item">
        	<a class="nav nav-link dark" href="?uri=logout">{sign out}</a>
        </li>
    </ul>
</nav>
<div class="navigation">
<div class="navi" style="width:20em;">
    <!-- Dashboard -->
	<div class="list-group spacing">
        <a href="/../admin/index" class="list-group-item list-group-item-action active">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-dashboard.svg"> {dashboard}
        </a>
	</div>

    <!-- Content -->
    <div class="list-group spacing">
        <span class="list-group-item active">
            {content}
        </span>
            <a href="/../article/index" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-pen.svg"> {article}
                <span class="badge badge-light">3</span>
            </a>
            <a href="/../download/index" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-file-download.svg"> {downloads}
                <span class="badge badge-light">0</span>
            </a>
            <a href="/../link/index" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-global.svg"> {links}
                <span class="badge badge-light">0</span>
            </a>
            <a href="/../page/index" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-document.svg"> {pages}
                <span class="badge badge-light">0</span>
            </a>
            <a href="/../trash/index" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-trash.svg"> {trash}
                <span class="badge badge-light">0</span>
            </a>
    </div>

    <!-- Communication -->
    <!-- <div class="list-group spacing">
        <span class="list-group-item active">
            <span class="glyphicon glyphicon-book" aria-hidden="true"></span> Kommunikation
        </span>
            <a href="index.php?uri=communication" class="list-group-item list-group-item-action">
                Kontakt anfragen
                <span class="badge badge-light">0##placeholder-inqiery##</span>
            </a>
    </div> -->

    <!-- Settings -->
    <div class="list-group spacing">
        <span class="list-group-item active">
            {settings}
        </span>
            <a href="/../admin/settings" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-gear.svg"> {general}
            </a>
            <a href="/../admin/mainpage" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-home-page.svg"> {mainpage}
            </a>
            <a href="/../article/settings" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-pen.svg"> {article}
            </a>
            <a href="/../download/settings" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-file-download.svg"> {downloads}
            </a>
            <a href="/../link/settings" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-global.svg"> {links}
            </a>
            
            <a href="/../user/index" class="list-group-item list-group-item-action">
                <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-person-people.svg"> {user}
            </a>
    </div>
</div>
</div>