<html>
	<head lang="de">
		<title>Heinrich-Schiller.de</title>
		<meta charset="utf8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="/vendor/twbs/bootstrap/dist/css/bootstrap-reboot.min.css">
		<link rel="stylesheet" href="/vendor/twbs/bootstrap/dist/css/bootstrap-grid.min.css">
		<link rel="stylesheet" href="/vendor/twbs/bootstrap/dist/css/bootstrap.min.css">

		<!-- jQuery library -->
		<script src="/vendor/components/jquery/jquery.min.js"></script>

		<!-- Latest compiled JavaScript -->
		<script src="/vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
		
		<!-- jQuery UI -->
		<link rel="stylesheet" href="/vendor/components/jqueryui/themes/base/jquery-ui.min.css">
		<script src="/vendor/components/jqueryui/jquery-ui.min.js"></script>

		<link href="/public/assets/css/default.css" rel="stylesheet">
	</head>
	<body>