<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<a class="navbar-brand" href="index.php?uri=mainpage">Heinrich-Schiller.de</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
		<div class="navbar-nav">
			<a class="nav-item nav-link" href="#">Blog</a>
			<a class="nav-item nav-link" href="#">Downloads</a>
			<a class="nav-item nav-link" href="#">Links</a>
			<a class="nav-item nav-link" href="#">Artikel</a>
			<a class="nav-item nav-link" href="#">Seiten</a>
			<a class="nav-item nav-link" href="/../admin/index">Sign in</a>
		</div>
	</div>
</nav>