<div class="col-sm-12 col-md-9 col-lg-9 col-xl-10">
   	<div class="panel">
   		<h4><img class="glyph-icon-24" src="<?= SVG_PATH; ?>si-glyph-pen.svg"> {links}</h4>
   	</div>

    <?php if(count($links) > 0): ?>

    <table class="table table-hover table-striped">
    	<thead>
    		<tr>
    			<th>#</th>
    			<th>{date}</th>
    			<th>{title}</th>
    			<th>{visible}?</th>
    			<th>{actions}</th>
    		</tr>
    	</thead>
    	<tbody>
    		<?php foreach($links as $link): ?>
    		<tr class="clickable-row" data-href="<?= BASE_URL; ?>link/edit/id/<?= $link['id']; ?>">
                <td></td>
                <td><?= strftime('%d.%m.%Y',$link['datetime']); ?></td>
                <td><?= $link['title']; ?></td>
                <td><?= ($link['visibility'] === 'true') ? '{yes}' : '{no}'; ?></td>
        		<td>
        			<a href="#">
        				<img class="glyph-icon-16" src="<?php echo SVG_PATH; ?>si-glyph-document-copy.svg" title="{copy}">
        			</a> &middot;
                	<a href="<?= BASE_URL; ?>link/del/id/<?= $link['id']; ?>">
                		<img class="glyph-icon-16" src="<?php echo SVG_PATH; ?>si-glyph-delete.svg" title="{delete}">
                	</a>
                </td>
            </tr>
            <?php endforeach; ?>
    	</tbody>
    </table>
	<div>
		<a href="<?= BASE_URL; ?>link/new" class="btn btn-primary" role="button">{create_link}</a>
	</div>


    <?php else: ?>

    <div class="row">
       	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    		<div class="alert alert-light" role="alert">
      			<h4>Es wurden noch keine Links erstellt!</h4>
      			<hr>
      			<p>Hier können sie ihre Links einfach verfassen und ausgeben.</p>
    		</div>
    		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        		<a href="<?= BASE_URL; ?>link/new" class="btn btn-primary" role="button">{create_link}</a>
    		</div>
       	</div>
    </div>

<?php endif; ?>
