<html>
	<head lang="de">
		<title>Heinrich-Schiller.de</title>
		<meta charset="utf8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="../vendor/twbs/bootstrap/dist/css/bootstrap-reboot.min.css">
		<link rel="stylesheet" href="../vendor/twbs/bootstrap/dist/css/bootstrap-grid.min.css">
		<link rel="stylesheet" href="../vendor/twbs/bootstrap/dist/css/bootstrap.min.css">

		<!-- jQuery library -->
		<script src="../vendor/components/jquery/jquery.min.js"></script>

		<!-- Latest compiled JavaScript -->
		<script src="../vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
		
		<!-- jQuery UI -->
		<link rel="stylesheet" href="../vendor/components/jqueryui/themes/base/jquery-ui.min.css">
		<script src="../vendor/components/jqueryui/jquery-ui.min.js"></script>

		<link href="../templates/default/admin/css/default.css" rel="stylesheet">
	</head>
	<body>
        <div class="container-fluid">
        	<nav class="navbar navbar-light bg-primary">
  				<a class="navbar-brand" href="#">Heinrich-Schiller.de - Administration</a>
  				<ul class="nav justify-content-end">
                      <li class="nav-item">
                        <a class="nav nav-link dark" href="?uri=logout">Sign out</a>
                      </li>
                  </ul>
			</nav>
        	<div class="row">
        		<div class="col-sm-12">
                    <noscript>
                    	<div class="container">
                    	  	<div class="alert alert-danger" role="alert">
                                <p>JavaScript ist nicht verfügbar oder es ist deaktiviert.</p>
                                <p>Bitte verwenden Sie einen Browser, der JavaScript unterstützt oder aktivieren Sie JavaScript in Ihrem Browser.</p>
                            </div>
                        </div>
                    </noscript>
                </div>
            </div>
            <div class="row navi">
        		<div class="col-xl-3 col-lg-3 col-xs-12">
        			<!-- Dashboard -->
<div class="list-group spacing">
        <a href="index.php?uri=dashboard" class="list-group-item list-group-item-action active">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-dashboard.svg"> Dashboard
        </a>
</div>

<!-- Content -->
<div class="list-group spacing">
    <span class="list-group-item active">
        Inhalt
    </span>
        <a href="index.php?uri=articles" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-pen.svg"> Artikel
            <span class="badge badge-light">3</span>
        </a>
        <a href="index.php?uri=downloads" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-file-download.svg"> Downloads
            <span class="badge badge-light">0</span>
        </a>
        <a href="index.php?uri=links" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-global.svg"> Links
            <span class="badge badge-light">0</span>
        </a>
        <a href="index.php?uri=pages" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-document.svg"> Seiten
            <span class="badge badge-light">0</span>
        </a>
        <a href="index.php?uri=trash" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-trash.svg"> Mülleimer
            <span class="badge badge-light">0</span>
        </a>
</div>

<!-- Communication -->
<div class="list-group spacing">
    <span class="list-group-item active">
        <span class="glyphicon glyphicon-book" aria-hidden="true"></span> Kommunikation
    </span>
        <a href="index.php?uri=communication" class="list-group-item list-group-item-action">
            Kontakt anfragen
            <span class="badge badge-light">0<!-- ##placeholder-inqiery##  --></span>
        </a>
</div>

<!-- Settings -->
<div class="list-group spacing">
    <span class="list-group-item active">
        Einstellungen
    </span>
        <a href="index.php?uri=general" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-gear.svg"> Allgemein
        </a>
        <a href="index.php?uri=mainpage" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-home-page.svg"> Hauptseite
        </a>
        <a href="index.php?uri=articlessettings" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-pen.svg"> Artikel
        </a>
        <a href="index.php?uri=downloadssettings" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-file-download.svg"> Downloads
        </a>
        <a href="index.php?uri=linksettings" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-global.svg"> Links
        </a>
        
        <a href="index.php?uri=user" class="list-group-item list-group-item-action">
            <img class="glyph-icon-16" src="../templates/default/admin/img/svg/si-glyph-person-people.svg"> Benutzer
        </a>
</div>

        		</div>
        	    <div class="col-xl-6 col-lg-9 col-xs-12 content-section">
        	    	<div class="row">
	<div class="col-xl-12 col-lg-12 col-xs-12">
		<div class="alert alert-warning" role="alert">
          	<h4 class="alert-heading">Hinweis!</h4>
         	 <hr>
         	 <p class="mb-0">Dashboard wird der Zukunft neu implementiert.</p>
         	 <p class="mb-0">Bitte haben sie geduld.</p>
        </div>
	</div>
</div>
        	    </div>
    	    </div>
    		<footer class="container-fluid bg-4 text-center">
      		    <a href="#">Heinrich Schiller 2017 - 2018</a>
        	</footer>
    	</div>
        
        <!-- TinyMCE-Editor -->
		<script src="../vendor/tinymce/tinymce/tinymce.min.js"></script>
  		<script>tinymce.init({ selector:'textarea#text'});</script>
  		
  		<script src="../templates/default/admin/js/main.js"></script>
	</body>
</html>
