<div>
    <ul>
        <li class="nav-item"><a class="nav-link" href="#">start</a></li>
        <li class="nav-item"><a class="nav-link" href="#">language</a></li>
        <li class="nav-item"><a class="nav-link" href="#">licence</a></li>
        <li class="nav-item"><a class="nav-link" href="#">conditions</a></li>
        <li class="nav-item"><a class="nav-link" href="#">database</a></li>
        <li class="nav-item"><a class="nav-link" href="#">user</a></li>
        <li class="nav-item"><a class="nav-link" href="#">installation</a></li>
        <li class="nav-item"><a class="nav-link" href="#">final</a></li>
    </ul>
</div>
