<div class="col-sm-12 col-md-9 col-lg-9 col-xl-10">
    <div class="row">
       	<div class="col-sm-12 col-md-12 col-lg-12 col-xl-9">
       		<div class="panel">
       			<h4><img class="glyph-icon-24" src="<?= SVG_PATH; ?>si-glyph-dropbox.svg"> {upload}</h4>
       		</div>
       	</div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-9">
            <br>
            <div class="alert alert-info" role="alert">
                <h4 class="alert-heading">Wichtige Hinweise</h4>
                <p>Die Funktion ist noch nicht fertig implementiert.</p>
                <hr>
                <p class="mb-0">Die Funktion kann nocht nicht benutzt werden.</p>
            </div>
            <form action="<?= $configs['baseUrl'];?>upload/add" method="post">
                <div class="input-group mb-3">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="inputGroupFile02">
                        <label class="custom-file-label" for="inputGroupFile02" aria-describedby="inputGroupFileAddon02">Choose file</label>
                    </div>
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary">{save}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
