<div class="container">
	<header>
        	<h2>{header_4}</h2>
        	<p>{text_12}</p>
	</header>
	<div class="row">
        	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        		<table class="table">
        			<thead>
        				<tr>
        					<th></th>
        					<th>{min-conditions}</th>
        					<th>{text_13}</th>
        				</tr>
        			</thead>
        			<tbody>
            			<tr>
            				<th>{webserver}</th>
            				<td>Apache-Webserver</td>
            				<td>##placeholder_webserver##</td>
            			</tr>
            			<tr>
            				<th>{text_14}</th>
            				<td>min. PHP 7.1.0</td>
            				<td>##placeholder_php_version##</td>
            			</tr>
            			<tr>
       						<th>{text_15}</th>
       						<td>pdo-mysqldb, pdo-sqlitedb, simplexml</td>
       						<td class="php-modules">##placeholder_php_modules##</td>
            			</tr>
            			<tr>
       						<th>{database}</th>
       						<td>{text_16}</td>
       						<td></td>
            			</tr>
        			</tbody>
        		</table>
        	</div>
	</div>
    <div class="row button_bottom">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
       		<a href="/../installer/database" class="btn btn-primary" role="button">{next}</a>
       	</div>
    </div>
</div>
