<div>
	<h2>{header_5}</h2>
	<p>{text_17}</p>
</div>
<div>
	<form>
		<div class="form-group">
			{database}:<br>
			<select name="db" class="custom-select">
				<option value="">SQLite</option>
				<option value="">MySQL</option>
			</select>
		</div>
		<input type="hidden" name="uri" value="database">
		<input type="hidden" name="lang" value="##placeholder-lang##">
	</form>
	<div>
		<a href="/../installer/user" class="btn btn-primary" role="button">{next}</a>
	</div>
</div>
