<div class="container">
	<div class="row">
		<div class="col-md-8">
			<header>
		        	<h2>{header_2}</h2>
			</header>
			<div class="row">
		        	<div class="col-md-12">
		        		<p>{text_5}</p>
		        		<p>{text_6}</p>
		        		<ul>
		        			<li>{text_7}</li>
		        			<li>{text_8}</li>
		        		</ul>
		        		<p>{text_9}</p>
		        		<p>{text_10}</p>
		        	</div>
		    </div>
		    <div class="row button_bottom">
		        	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		        		<a href="/../installer/language" class="btn btn-primary" role="button">{next}</a>
		        	</div>
		    </div>
		</div>
		<div class="col-md-4">
			<nav>
       			<ul>
					<li class="nav-item"><a class="nav-link" href="#">start</a></li>
        			<li class="nav-item"><a class="nav-link" href="#">language</a></li>
        			<li class="nav-item"><a class="nav-link" href="#">licence</a></li>
        			<li class="nav-item"><a class="nav-link" href="#">conditions</a></li>
       				<li class="nav-item"><a class="nav-link" href="#">database</a></li>
       				<li class="nav-item"><a class="nav-link" href="#">user</a></li>
       				<li class="nav-item"><a class="nav-link" href="#">installation</a></li>
       				<li class="nav-item"><a class="nav-link" href="#">final</a></li>
       			</ul>
       		</nav>
		</div>
	</div>
</div>
