<div class="content-container">
<div class="row">
	<div class="col-lg-10 col-md-10 col-sm-10 col-12">
		<div class="panel">
			<h4>
				<img class="glyph-icon-24" src="<?= SVG_PATH; ?>si-glyph-person-people.svg">
				{user}
			</h4>
		</div>
	</div>
</div>
<table class="table table-hover table-striped">
    <thead>
    	<tr>
            <th>#</th>
            <th>{firstname}</th>
            <th>{lastname}</th>
            <th>{username}</th>
            <th>{active}</th>
            <!-- <th>Role</th>  -->
            <th>{actions}</th>
        <tr>
    </thead>
    <tbody>
    <?php foreach ($users as $user): ?>
		<tr>
            <td><?= $user['id']; ?></td>
            <td><?= $user['firstname']; ?></td>
            <td><?= $user['lastname']; ?></td>
            <td><?= $user['username']; ?></td>
            <td><?= $user['active']; ?></td>
    		<td>
    			<a href="<?= BASE_URL?>user/edit/id/<?= $user['id']; ?>">
                	<img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-edit.svg" title="{edit}">
                </a> &middot;
    			<a href="<?= BASE_URL?>user/del/id/<?= $user['id']; ?>">
                	<img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-delete.svg" title="{delete}">
                </a>
            </td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>

<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<a href="<?= BASE_URL; ?>user/new" class="btn btn-primary" role="button">{create_user}</a>
	</div>
</div>
</div>
