<div class="col-sm-12 col-md-8 col-lg-8 col-xl-10">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-9">
			<div class="panel">
				<h4>
					<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
					{user}: <?= $user['firstname']; ?> <?= $user['lastname']; ?>
				</h4>
			</div>

			<?php if(isset($article['id'])): ?>
            <form action="<?= BASE_URL;?>article/update" method="post">
            <?php else: ?>
            <form action="<?= BASE_URL;?>article/add" method="post">
            <?php endif; ?>

                <div class="row">
                    <div class="col-2 col-sm-3 col-md-3 col-lg-3 col-xl-9">
						<div class="form-group">
							<label for="ident">#&nbsp;</label><span><?= $user['id']; ?></span>
							<input type="hidden" name="id" value="##placeholder-id##" class="form-control" id="ident">
						</div>
					</div>
					<div class="col-10 col-sm-9 col-md-9 col-lg-9 col-xl-3">
						<div class="form-group">
							<p class="text-right">{date}: <?= strftime('%d.%m.%Y', $user['datetime']); ?></p>
						</div>
					</div>
				</div>
				<div class="form-group">
					<label for="firstname">{firstname}:</label>
					<input type="text" name="firstname" value="<?= $user['firstname']; ?>" class="form-control" id="firstname" required>
				</div>
				<div class="form-group">
					<label for="lastname">{lastname}:</label>
					<input type="text" name="lastname" value="<?= $user['lastname']; ?>" class="form-control" id="lastname" required>
				</div>
				<div class="form-group">
					<label for="username">{username}:</label>
					<input type="text" name="username" value="<?= $user['username']; ?>" class="form-control" id="username" required>
				</div>
				<div class="form-group">
					<label for="email">{email}:</label>
					<input type="email" name="email" value="<?= $user['email']; ?>" class="form-control" id="email">
				</div>
				<div class="form-group">
					<label for="public_as">{show_publicly_as}:</label>
					<input type="text" name="public_as" value="<?= $user['username']; ?>" class="form-control" id="public_as">
				</div>
				<div class="form-group">
					<label for="password">{password}:</label>
					<button type="button" class="btn btn-default" id="password" onclick="systemMessage()">{generate_password}</button>
				</div>
			</div>
				<div class="col-sm-12 col-md-12 col-lg-12 col-xl-3">
                    <div class="list-group spacing">
                        {options}
                	</div>
					<div class="checkbox">
						<span>{active}?</span>
						<input type="radio" name="active" value="true" <?= ($user['active'] === 'true') ? 'checked' : ''; ?>> {yes}
						<input type="radio" name="active" value="false" <?= ($user['active'] === 'false') ? 'checked' : ''; ?>> {no}
					</div>
				</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xl-12">
					<div class="form-group">
						<button type="submit" class="btn btn-success">{save}</button>
						<span></span>
						<button type="reset" class="btn btn-danger">{reset}</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
