<div class="content-container">
<div class="row">
   	<div class="col-lg-10 col-md-10 col-sm-10 col-12">
   		<div class="panel">
   			<h4><img class="glyph-icon-24" src="../templates/default/admin/img/svg/si-glyph-pen.svg"> {links}</h4>
   		</div>
   	</div>
</div>
<table class="table table-hover table-striped">
	<thead>
		<tr>
			<th>#</th>
			<th>{date}</th>
			<th>{title}</th>
			<th>{visible}?</th>
			<th>{actions}</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($links as $link): ?>
		<tr>
            <td></td>
            <td><?= strftime('%d.%m.%Y',$link['datetime']); ?></td>
            <td><?= $link['title']; ?></td>
            <td><?= ($link['visibility'] === 'true') ? '{yes}' : '{no}'; ?></td>
    		<td>
    			<a href="#">
    				<img class="glyph-icon-16" src="<?php echo SVG_PATH; ?>si-glyph-edit.svg" title="{edit}">
    			</a> &middot;
    			<a href="#">
    				<img class="glyph-icon-16" src="<?php echo SVG_PATH; ?>si-glyph-document-copy.svg" title="{copy}">
    			</a> &middot;
            	<a href="#">
            		<img class="glyph-icon-16" src="<?php echo SVG_PATH; ?>si-glyph-delete.svg" title="{delete}">
            	</a>
            </td>
        </tr>
        <?php endforeach; ?>
	</tbody>
</table>
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<a href="/../link/new" class="btn btn-primary" role="button">{create_link}</a>
	</div>
</div>
</div>