<div class="row">
   	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="alert alert-light" role="alert">
  			<h4>Es wurden noch keine Links erstellt!</h4>
  			<hr>
  			<p>Hier können sie ihre Links einfach verfassen und ausgeben.</p>
		</div>
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    		<a href="<?= BASE_URL; ?>link/new" class="btn btn-primary" role="button">{create_link}</a>
		</div>
   	</div>
</div>
