<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">{downloads}</h1>
    <p class="lead">##placeholder-downloads-page-tagline##</p>
  </div>
</div>
<div class="container">
    <div class="row">
    	<div class="col-sm-12">
    		##placeholder-downloads-page-comment##
    	</div>
    </div>
</div>
<div class="container">
    <div class="row">
    	<div class="col-sm-12">
    		<ol>
    		   <div class="row">
                	<div class="col-md-12">
                		<ul class="list-group">
                			<li class="list-group-item active">##placeholder-title##  <span class="article-datetime">##placeholder-datetime##</span></li>
                			<li class="list-group-item">##placeholder-comment##</li>
                			<li class="list-group-item"><a href="##placeholder-downloads-path##/##placeholder-downloads-filename##">Download</a></li>
                		</ul>
                	</div>
                </div>
                <br>
    		</ol>
    	</div>
    </div>
</div>