<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">{links}</h1>
    <p class="lead">##placeholder-links-page-tagline##</p>
  </div>
</div>
<div class="container">
	##placeholder-links-page-comment##
</div>
<div class="container">
	<div class="row">
    	<div class="col-md-12">
    		<ul class="list-group">
    			<li class="list-group-item active">
    				<a href="##placeholder-links-uri##" target="blank">##placeholder-links-title## - ##placeholder-links-tagline##</a>
    			</li>
    			<li class="list-group-item">##placeholder-links-comment##</li>
    		</ul>
    	</div>
    </div>
    <br>
</div>