<div class="content-container">
    <div class="row">
       	<div class="col-lg-10 col-md-10 col-sm-10 col-12">
       		<div class="panel">
       			<h4><img class="glyph-icon-24" src="<?= SVG_PATH; ?>si-glyph-dropbox.svg"> {upload}</h4>
       		</div>
       	</div>
    </div>
    <div class="row">
        <div class="col-lg-10 col-md-10 col-sm-10 col-12">
            <br>
            <div class="alert alert-info" role="alert">
                <h4 class="alert-heading">Wichtige Hinweise</h4>
                    <p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>
                    <hr>
                    <p class="mb-0">Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>
            </div>
        </div>
    </div>
    <div class="row">
       	<div class="col-lg-10 col-md-10 col-sm-10 col-12">
            <form action="<?= BASE_URL;?>upload/add" method="post">
                <div class="input-group mb-3">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="inputGroupFile02">
                        <label class="custom-file-label" for="inputGroupFile02" aria-describedby="inputGroupFileAddon02">Choose file</label>
                    </div>
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-primary">{save}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
