<div class="content-container">
	<div class="row">
	   	<div class="col-lg-10 col-md-10 col-sm-10 col-12">
	   		<div class="panel">
	   			<h4><img class="glyph-icon-24" src="<?php echo SVG_PATH; ?>si-glyph-dashboard.svg"> {dashboard}</h4>
	   		</div>
	   	</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<div class="alert alert-light">
				<h4 class="alert-heading">{article}</h4>
				...
			</div>
		</div>
		<div class="col-md-3">
			<div class="alert alert-light">
				<h4 class="alert-heading">{downloads}</h4>
				...
			</div>
		</div>
		<div class="col-md-3">
			<div class="alert alert-light">
				<h4 class="alert-heading">{links}</h4>
				...
			</div>
		</div>
		<div class="col-md-3">
			<div class="alert alert-light">
				<h4 class="alert-heading">{pages}</h4>
				...
			</div>
		</div>
	</div>
</div>
