<div class="col-sm-12 col-md-9 col-lg-9 col-xl-10">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-9">
        	<div class="panel">
        		<h4><img class="glyph-icon-24" src="<?= SVG_PATH; ?>si-glyph-pen.svg"> {article}</h4>
        	</div>

            <?php if(isset($article['id'])): ?>
            <form action="<?= BASE_URL;?>article/update" method="post">
            <?php else: ?>
            <form action="<?= BASE_URL;?>article/add" method="post">
            <?php endif; ?>

                <div class="row id-bar">
                    <div class="col-2 col-sm-3 col-md-3 col-lg-3 col-xl-9">
                		<div class="form-group">
                			<label for="ident">#&nbsp;</label><span><?= isset($article['id']) ? $article['id'] : '{new}'; ?></span>
                			<input type="hidden" name="id" value="<?= isset($article['id']) ? $article['id'] : ''; ?>" class="form-control" id="ident">
                		</div>
                    </div>
                    <div class="col-10 col-sm-9 col-md-9 col-lg-9 col-xl-3">
                		<div class="form-group">
                			<p class="text-right">{date}: <?= isset($article['datetime']) ? strftime('%d.%m.%Y', $article['datetime']) : getCurrentDatetime(); ?></p>
                		</div>
                    </div>
                </div>
        		<div class="form-group">
        			<label for="title">{title}:</label>
        			<input type="text" name="title" value="<?= isset($article['title']) ? $article['title'] : ''; ?>" class="form-control" id="title" required>
        		</div>
        		<div class="form-group">
        			<label for="text">{text}:</label>
        			<textarea name="text" id="texteditor">
                        <?= isset($article['text']) ? $article['text'] : ''; ?>
                    </textarea>
        		</div>
            </div>
            <!-- sidebar -->
                <div class="col-sm-12 col-md-12 col-lg-12 col-xl-3">
            		<div class="form-group">
            			<label for="ident">#&nbsp;</label><span><?= isset($article['id']) ? $article['id'] : '{new}'; ?></span>
                		<input type="hidden" name="id" value="<?= isset($article['id']) ? $article['id'] : ''; ?>" class="form-control" id="ident">
                	</div>
                    <div class="form-group">
                        <button type="button" id="btn-preview" class="btn btn-light" data-href="<?= BASE_URL ?>public/article/preview">{preview}</button>
                    </div>
        			<span>{published}?</span>
                	<div class="custom-control custom-radio custom-control-inline">
                  		<input type="radio" id="customRadioInline1" name="visibility" value="true" class="custom-control-input" <?= (isset($article['visibility']) && $article['visibility'] === 'true') ? 'checked' : ''; ?>>
                  		<label class="custom-control-label" for="customRadioInline1">{yes}</label>
                	</div>
                	<div class="custom-control custom-radio custom-control-inline">
                  		<input type="radio" id="customRadioInline2" name="visibility" value="false" class="custom-control-input" <?= (isset($article['visibility']) && $article['visibility'] === 'false' || !isset($article)) ? 'checked' : ''; ?> >
                  		<label class="custom-control-label" for="customRadioInline2">{no}</label>
                	</div>
                    <div class="form-group">
                        <span>{published_at}:</span>
                    </div>
                    <div class="form-group">
                        <span>{created_at}:</span>
                		<span class="elem-pos-right">
                            <?= isset($article['datetime']) ? strftime('%d.%m.%Y', $article['datetime']) : getCurrentDatetime(); ?>
                        </span>
                	</div>
                    <div class="form-group">
                        <span>{updated_at}:</span>
                    </div>
                    <div class="form-group">
                        <span>{author}:</span>
                        <span class="elem-pos-right">
                            <?= isset($article['author']) ? $article['author'] : getCurrentAuthor(); ?>
                        </span>
                    </div>
                </div>
                <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
            		<div class="form-group">
            			<button type="submit" class="btn btn-success">{save}</button>
            			<span></span>
            			<button type="reset" class="btn btn-danger">{reset}</button>
            		</div>
                </div>
            </form>
        </div>
    </div>
</div>
