<div class="col-sm-12 col-md-9 col-lg-9 col-xl-10">
	<div class="panel">
		<h4><img class="glyph-icon-24" src="<?= $config['baseUrl']; ?>public/assets/img/svg/si-glyph-pen.svg"> {articles}</h4>
	</div>

    <?php if(count($articles) > 0): ?>

    <table class="table table-hover table-striped">
    	<thead>
    		<tr>
    			<th>#</th>
    			<th>{date}</th>
    			<th>{title}</th>
    			<th>{visible}?</th>
    			<th>{actions}</th>
    		</tr>
    	</thead>
    	<tbody>

            <?php foreach($articles as $article): ?>

        	<tr class="clickable-row" data-href="<?= $config['baseUrl']; ?>article/edit/id/<?= $article['id']; ?>">
                <td></td>
                <td><?= strftime('%d.%m.%Y', $article['datetime']); ?></td>
                <td><?= $article['title']; ?></td>
                <td><?= $article['visibility'] === 'true' ? '{yes}' : '{no}'; ?></td>
        		<td>
        			<a href="<?= $config['baseUrl']; ?>article/copy/id/<?= $article['id'];?>">
        				<img class="glyph-icon-16" src="<?= $config['baseUrl']; ?>public/assets/img/svg/si-glyph-document-copy.svg" title="{copy}">
        			</a> &middot;
                	<a href="<?= $config['baseUrl']; ?>article/del/id/<?= $article['id'];?>">
                		<img class="glyph-icon-16" src="<?= $config['baseUrl']; ?>public/assets/img/svg/si-glyph-delete.svg" title="{delete}">
                	</a>
                </td>
            </tr>

            <?php endforeach; ?>

    	</tbody>
    </table>
    <div>
    	<a href="<?= BASE_URL; ?>article/new" class="btn btn-primary" role="button">{create_article}</a>
    </div>

    <?php else: ?>

    <div class="col-lg-12 col-md-12 col-sm-12 col-xl-12">
        <div class="alert alert-light" role="alert">
            <h4>Es wurden noch keine Artikel erstellt!</h4>
            <hr>
            <p>Hier können sie ihre Artikel, Blogeinträge und Texte einfach verfassen und ausgeben.</p>
            <p>Diese werden anschließend der öffentlichkeit präsentiert. Wollen sie den angefangenen
            Artikel noch nicht publizieren, stellen sie den Artikel einfach auf unsichtbar.</p>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <a href="<?= BASE_URL; ?>article/new" class="btn btn-primary" role="button">{create_article}</a>
        </div>
    </div>

	<?php endif; ?>

</div>
