<div class="col-sm-12 col-md-9 col-lg-9 col-xl-10">
	<div class="row">
		<div class="col-sm-12 col-md-12 col-lg-12 col-xl-9">
			<div class="panel">
				<h4><img class="glyph-icon-24" src="<?= SVG_PATH; ?>si-glyph-file-download.svg""> {downloads_settings}</h4>
			</div>
		</div>
	</div>
	<form action="<?= $configs['baseUrl']; ?>download/updatesettings" method="post">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<div class="form-group">
					<label for="title">{tagline}:</label>
					<input type="text" name="tagline" class="form-control" id="title" value="<?= (!empty($settings['tagline'])) ? $settings['tagline'] : ''; ?>">
				</div>
				<div class="form-group">
					<label for="comment">{text}:</label>
					<textarea name="text" rows="5" class="form-control" id="comment"><?= (!empty($settings['text'])) ? $settings['text'] : ''; ?></textarea>
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-success">{save}</button>
					<span></span>
					<button type="reset" class="btn btn-danger">{reset}</button>
				</div>
			</div>
		</div>
	</form>
</div>
