<div class="col-sm-12 col-md-9 col-lg-9 col-xl-10">
    <div class="panel">
        <h4><img class="glyph-icon-24" src="<?= SVG_PATH; ?>si-glyph-file-download.svg"> {downloads}</h4>
    </div>


    <?php if(count($downloads) > 0): ?>

    <table class="table table-hover table-striped">
    	<thead>
    		<tr>
    			<th>#</th>
    			<th>{date}</th>
    			<th>{title}</th>
    			<th>{visible}?</th>
    			<th>{actions}</th>
    		</tr>
    	</thead>
    	<tbody>
    		<?php foreach($downloads as $download): ?>
    		<tr class="clickable-row" data-href="<?= $configs['baseUrl']; ?>download/edit/id/<?= $download['id']; ?>">
                <td></td>
                <td><?= strftime('%d.%m.%Y', $download['datetime']); ?></td>
                <td><?= $download['title']; ?></td>
                <td><?= ($download['visibility'] === 'true') ? '{yes}' : '{no}'; ?></td>
        		<td>
        			<a href="#">
        				<img class="glyph-icon-16" src="<?php echo SVG_PATH;?>si-glyph-document-copy.svg" title="{copy}">
        			</a> &middot;
                	<a href="<?= $configs['baseUrl']; ?>download/del/id/<?= $download['id']; ?>">
                		<img class="glyph-icon-16" src="<?php echo SVG_PATH;?>si-glyph-delete.svg" title="{delete}">
                	</a>
                </td>
            </tr>
            <?php endforeach; ?>
    	</tbody>
    </table>

    <div>
    	<a href="<?= $configs['baseUrl']; ?>download/new" class="btn btn-primary" role="button">{create_download}</a>
    </div>

    <?php else: ?>

    <div class="row">
       	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    		<div class="alert alert-light" role="alert">
      			<h4>Es wurden noch keine Downloads erstellt!</h4>
      			<hr>
      			<p>Hier können sie ihre Downloads einfach verfassen und ausgeben.</p>
      			<p>Diese werden anschließend der öffentlichkeit präsentiert. Wollen sie den angefangenen
      			Artikel noch nicht publizieren, stellen sie den Artikel einfach auf unsichtbar.</p>
    		</div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        		<a href="<?= $configs['baseUrl']; ?>download/new" class="btn btn-primary" role="button">{create_download}</a>
    		</div>
       	</div>
    </div>

    <?php endif; ?>

</div>
