<html>
	<head lang="<?= $settings['lang_short']; ?>">
		<title>heinerCMS - Installer</title>
		<meta charset="utf8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="/vendor/twbs/bootstrap/dist/css/bootstrap-reboot.min.css">
		<link rel="stylesheet" href="/vendor/twbs/bootstrap/dist/css/bootstrap-grid.min.css">
		<link rel="stylesheet" href="/vendor/twbs/bootstrap/dist/css/bootstrap.min.css">

		<!-- jQuery library -->
		<script src="/vendor/components/jquery/jquery.min.js"></script>

		<!-- Latest compiled JavaScript -->
		<script src="/vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>

		<!-- jQuery UI -->
		<link rel="stylesheet" href="/vendor/components/jqueryui/themes/base/jquery-ui.min.css">
		<script src="/vendor/components/jqueryui/jquery-ui.min.js"></script>

		<link href="/../installer/public/assets/css/style.css" rel="stylesheet">
	</head>
	<body>
		<div class="viewport">
			<header>
				<nav class="navbar navbar-dark bg-dark">
					<span class="navbar-brand">heinerCMS - Installation</span>
				</nav>
			</header>
			<aside class="box-left"></aside>
			<div class="box-content">
				<?php require $template; ?>
			</div>
	        <aside class="box-right">
	        	<?php require $navbar; ?>
	        </aside>
	        <footer>
	            <div class="footer-text">
	                <p>&copy; Heinrich Schiller 2017 - 2019</p>
	                <p><i>powered by heinerCMS</i></p>
	            </div>
	        </footer>
		</div>
        <!-- TinyMCE-Editor -->
        <script src="/vendor/tinymce/tinymce/tinymce.min.js"></script>
		<script src="/public/assets/js/editor.js"></script>
        <script src="/public/assets/js/main.js"></script>
    </body>
</html>
