<div class="content-container">
<div class="row">
   	<div class="col-lg-10 col-md-10 col-sm-10 col-12">
   		<div class="panel">
   			<h4><img class="glyph-icon-24" src="../templates/default/admin/img/svg/si-glyph-pen.svg"> {pages}</h4>
   		</div>
   	</div>
</div>
<table class="table table-hover table-striped">
	<thead>
		<tr>
			<th>#</th>
			<th>{date}</th>
			<th>{title}</th>
			<th>{visible}?</th>
			<th>{actions}</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($pages as $page): ?>
		<tr>
            <td></td>
            <td><?= $page['datetime']; ?></td>
            <td><?= $page['title']; ?></td>
            <td><?= $page['visibility']; ?></td>
    		<td>
    			<a href="#">asd</a> &middot;
    			<a href="#">asd</a> &middot;
            	<a href="#">asd</a>
            </td>
        </tr>
        <?php endforeach; ?>
	</tbody>
</table>
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<a href="/../page/new" class="btn btn-primary" role="button">{create_page}</a>
	</div>
</div>
</div>