<div class="jumbotron">
	<div class="container">
		<h1 class="display-4">{article}</h1>
		<p class="lead"><?= $settings['tagline']; ?></p>
	</div>
</div>
<div class="container">
	<?= (!empty($settings['text'])) ? $settings['text'] : ''; ?>
</div>
<div class="container-fluid">
<?php foreach ($articles as $article): ?>
	<div class="row">
    	<div class="col-md-12">
    		<div class="container">
                <div>
                    <label>{author}:</label>&nbsp;<?= $article['author']; ?>&nbsp;
                    <?= strftime('%d.%m.%Y', $article['datetime']); ?>
                </div>
            	<div>
                    <h2>
						<a class="content-header" href="<?= $configs['baseUrl']; ?>public/article/id/<?= $article['id']; ?>">
							<?= $article['title']; ?>
						</a>
					</h2>
                </div>
            	<div class="lead">
                    <?= $article['text']; ?> ...</div>
            	<div>
                    <a href="<?= $configs['baseUrl']; ?>public/article/id/<?= $article['id']; ?>">{readmore}</a>
                </div>
				<hr class="featurette-divider">
    		</div>
    	</div>
    </div>
    <br>
<?php endforeach; ?>
</div>
