<div class="col-md-##placeholder-col-num##">
	<div class="card">
		<img class="card-img-top" src="data/images/teaser/teaser-1.png"
			title="##placeholder-title##" alt="##placeholder-title##" />
		<div class="card-body">
			<span class="card-title"><h4>##placeholder-title##</h4></span>
			<p class="card-text">##placeholder-content##</p>
			<a href="#" class="btn btn-teaser">Weiterlesen</a>
		</div>
	</div>
</div>