<div class="col-sm-12 col-md-3 col-lg-2 col-xl-9">
	<div class="panel">
		<h4><img class="glyph-icon-24" src="<?= SVG_PATH; ?>si-glyph-person-people.svg"> {user}</h4>
	</div>

	<table class="table table-hover table-striped" id="table">
	    <thead>
	    	<tr>
	            <th>#</th>
	            <th>{firstname}</th>
	            <th>{lastname}</th>
	            <th>{username}</th>
	            <th>{active}</th>
	            <!-- <th>Role</th>  -->
	            <th>{actions}</th>
	        <tr>
	    </thead>
	    <tbody>
	    <?php foreach ($users as $user): ?>
			<tr>
	            <td><?= $user['id']; ?></td>
	            <td><?= $user['firstname']; ?></td>
	            <td><?= $user['lastname']; ?></td>
	            <td><?= $user['username']; ?></td>
	            <td><?= $user['active']; ?></td>
	    		<td>
	    			<a href="<?= $configs['baseUrl']?>user/edit/id/<?= $user['id']; ?>">
	                	<img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-edit.svg" title="{edit}">
	                </a> &middot;
	    			<a href="<?= $configs['baseUrl']?>user/del/id/<?= $user['id']; ?>">
	                	<img class="glyph-icon-16" src="<?= SVG_PATH; ?>si-glyph-delete.svg" title="{delete}">
	                </a>
	            </td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>

	<div>
		<a href="<?= $configs['baseUrl']; ?>user/new" class="btn btn-primary" role="button">{create_user}</a>
	</div>
</div>
